version: '3.7'

volumes:
  nextcloud:
  db:

services:
  db:
    image: mariadb:10.4.8
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    ports:
      - 13306:3306

    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=ingimar
      - MYSQL_PASSWORD=ingimar
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  app:
    image: nextcloud
    ports:
      - 9080:80
    links:
      - db
    volumes:
      - nextcloud:/var/www/html
    restart: always
